site_name: "CleanOutbound.com"

theme:
  name: material
  logo: assets/fish-face.png
  favicon: assets/fish-face.png
  features:
   - navigation.expand
  

extra_css:
  - stylesheets/extra.css
  
nav:
  - "": index.md
  - Posts:
      - "Outbound is Dirty": posts/outbound-is-dirty.md
      # - "Parasitic Sales": posts/parasitic-sales.md
      # - "Degrees of Clean": posts/degrees-of-clean.md 
      - "The Day of the Blast": posts/the-day-of-the-blast.md
      - "The Red Queen": posts/the-red-queen.md
      # - "Praxos vs. Cleanthes": posts/praxos-vs-cleanthes.md
      - "The Gospel of Growth": posts/the-gospel-of-growth.md
      - "Explainer: Email Warming": posts/email-warming.md
      - "Explainer: Intent Data": posts/intent-data.md
      - "The Cost of Cold Email (Part I)": posts/the-cost-of-cold-email-part-1.md
      - "The Screech": posts/the-screech.md
